name: LEO Jamestown
short_description: Luxury Homes for Rent in Greer, SC at the LEO Jamestown .
description:  Welcome home to the LEO Jamestown, homes for rent in Greer, SC. When you enter our warm and inviting community, you’ll discover how our luxury single-family homes blend upscale living with maximum comfort.
url: https://leojamestown.github.io/
