name: Hannah Joy Roth
short_description: Making a mess.
description:  I’m Hannah Joy Roth, an abstract artist passionate about emotion and color and where they collide.
url: https://www.hannahjoyroth.com
